# Generated by Django 3.0.7 on 2020-06-04 14:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=5)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Time', models.DateField()),
                ('shop', django.contrib.postgres.fields.jsonb.JSONField()),
                ('hospital', django.contrib.postgres.fields.jsonb.JSONField()),
                ('transport_station', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
