# Generated by Django 3.0.7 on 2020-06-05 17:58

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=5)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=6)),
                ('time', models.DateField()),
                ('shop', django_mysql.models.JSONField(default=dict, null=True)),
                ('hospital', django_mysql.models.JSONField(default=dict, null=True)),
                ('transport_station', django_mysql.models.JSONField(default=dict, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
