# Generated by Django 3.0.7 on 2020-06-05 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlv_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Time',
            new_name='time',
        ),
    ]
