# Generated by Django 3.0.7 on 2020-06-05 08:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlv_app', '0002_auto_20200605_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='hospital',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='shop',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='transport_station',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
