# Generated by Django 3.0.7 on 2020-06-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlv_app', '0002_auto_20200611_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='disasters',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shops',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
