# Generated by Django 3.0.7 on 2020-06-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlv_app', '0003_add_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid',
            name='category',
            field=models.CharField(choices=[('Mild', 'Mild'), ('Medium', 'Medium'), ('Severe', 'Severe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='disasters',
            name='category',
            field=models.CharField(choices=[('cyclone', 'cyclone'), ('earthquake', 'earthquake'), ('temperature_rise', 'temperature_rise'), ('GHGemissions', 'GHGemissions')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shops',
            name='category',
            field=models.CharField(choices=[('shops', 'shops'), ('covid_cases', 'covid_cases'), ('shops_closed', 'shops_closed'), ('medical_centres', 'medical_centres')], max_length=20),
        ),
    ]
