# Generated by Django 3.0.7 on 2020-06-19 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlv_app', '0005_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='username',
            new_name='user',
        ),
    ]
