# Generated by Django 2.2 on 2020-06-22 22:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tlv_app', '0009_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='config',
            unique_together={('name', 'user')},
        ),
    ]
